apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truzzles
  namespace: truzzles
spec:
  secretName: truzzles
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "truzzles.trueberryless.org"
