apiVersion: apps/v1
kind: Deployment
metadata:
  name: truzzles
  namespace: truzzles
  labels:
    app: truzzles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: truzzles
  template:
    metadata:
      labels:
        app: truzzles
    spec:
      containers:
        - name: truzzles
          image: "trueberryless/truzzles:main-c36e27f6341898b93a8d9e128a9cfeef5d706528"
          imagePullPolicy: Always
